import React from 'react'
import Product2 from '../../components/ProductsPage/Sowingseeds'
import Head from 'next/head';
const product2 = () => {
  return (
    <div>
      <Head>
        <title> Agrifint | Sowing seeds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Product2 />
    </div>
  );
}

export default product2
