import React from 'react'
import Product3 from '../../components/ProductsPage/AgroGain'
import Head from 'next/head';
const product3 = () => {
  return (
    <div>
      <Head>
        <title> Agrifint | Agri Gain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Product3 />
    </div>
  );
}

export default product3
