import React from 'react'
import Product4 from '../../components/ProductsPage/AGventure'
import Head from 'next/head';

const product4 = () => {
  return (
    <div>
      <Head>
        <title> Agrifint | AGventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Product4 />
    </div>
  );
}

export default product4