import React from 'react'
import Product1 from '../../components/ProductsPage/FreshHarvest'
import Head from 'next/head';
const product1 = () => {
  return (
    <div>
      <Head>
        <title> Agrifint | Fresh Harvest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Product1 />
    </div>
  );
}

export default product1
