import React from 'react'
import ContactUs from '../components/ContactPages/ContactUs'
import ContactUSS from '../components/ContactPages/ContactUSS'
import Head from "next/head";

const contact = () => {
  return (
    <div>
    <Head>
        <title> Agrifint | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="lg:pt-32 pt-10 bg-dark">
      <ContactUSS />
      <ContactUs />
      </div>
      </div>
  );
}

export default contact
