import React from 'react'
import Head from 'next/head';
import ContactUs from '../components/ContactPages/ContactUs';
const contacthome = () => {
  return (
    <div>
      <Head>
        <title> Agrifint | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="lg:pt-32 pt-10 bg-dark">
        <ContactUs />
      </div>
    </div>
  );
}

export default contacthome
