import Head from "next/head";
import Image from "next/image";
import Banner from "../components/HomePages/Banner";
import Calculator from "../components/HomePages/Calculator";
import Contact from "../components/HomePages/Contact";
import Features from "../components/HomePages/Features";
import OrganicFood from "../components/HomePages/OrganicFood";
import Projects from "../components/HomePages/Projects";
import Services from "../components/HomePages/Services";
import StartSteps from "../components/HomePages/StartSteps";
import Success from "../components/HomePages/Success";
import Testimonial from "../components/HomePages/Testimonial";
import styles from "../styles/Home.module.css";
import Button from "../utilities/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Agrifint | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div>
        <Banner />
        <OrganicFood/>
        <Features />
        <Services />
        <StartSteps />
        <Calculator />
        <Testimonial />
        <Success />
        <Projects />
        <Contact />
      </div>
    </div>
  );
}
