import React from 'react'
import Shopp from '../components/ShopPages/Shop'
import Head from 'next/head';
const shop = () => {
  return (
    <div>
      <Head>
        <title> Agrifint | Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Shopp />
    </div>
  );
}

export default shop
