import React from "react";
import Head from "next/head";
const ThankYou = () => {
  return (
    <div>
      <Head>
        <title> Agrifint | ThankYou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="pt-40 px-5 bg-darkBg text-primary text-center text-3xl ">
      <h1>Thank you for contacting Us </h1>
      <h2>OUr Team will reply soon</h2>
      </div>
    </div>
  );
};

export default ThankYou;
